### ISSUE TITLE
Kconfig errors while running ZAUTH

### ISSUE THREAD

**Issue by Chandranshu9** [GoldenBitsSoftware/zephyr#1]
I am receiving some Kconfig warnings, The same warnings were also shown when I was running the test version of authentication. Please help me with this.

I think I am not able to integrate ZAUTH with zephyrRTOS, I simply downloaded and pasted ZAUTH inside zephyr folder. Are there any changes in config files that are to be done before building the project?
Below is the error that I am receiving while building the code:-

Parsing /home/chandranshu/zephyrproject/zephyr/Kconfig
Loaded configuration '/home/chandranshu/zephyrproject/zephyr/boards/arm/arduino_nano_33_iot/arduino_nano_33_iot_defconfig'
Merged configuration '/home/chandranshu/zephyrproject/zephyr/zephyr-feature-auth_lib/samples/authentication/bluetooth/central_auth/prj.conf'

/home/chandranshu/zephyrproject/zephyr/zephyr-feature-auth_lib/samples/authentication/bluetooth/central_auth/prj.conf:6: warning: attempt to assign the value 'y' to the undefined symbol BT_GATT_DIS

/home/chandranshu/zephyrproject/zephyr/zephyr-feature-auth_lib/samples/authentication/bluetooth/central_auth/prj.conf:22: warning: attempt to assign the value 'y' to the undefined symbol AUTH_LIB

/home/chandranshu/zephyrproject/zephyr/zephyr-feature-auth_lib/samples/authentication/bluetooth/central_auth/prj.conf:23: warning: attempt to assign the value 'y' to the undefined symbol BT_XPORT

/home/chandranshu/zephyrproject/zephyr/zephyr-feature-auth_lib/samples/authentication/bluetooth/central_auth/prj.conf:24: warning: attempt to assign the value 'y' to the undefined symbol AUTH_CHALLENGE_RESPONSE

/home/chandranshu/zephyrproject/zephyr/zephyr-feature-auth_lib/samples/authentication/bluetooth/central_auth/prj.conf:27: warning: attempt to assign the value 'y' to the undefined symbol AUTH_CHALLENGE_RESPONSE

/home/chandranshu/zephyrproject/zephyr/zephyr-feature-auth_lib/samples/authentication/bluetooth/central_auth/prj.conf:31: warning: attempt to assign the value '3' to the undefined symbol AUTH_LOG_LEVEL

/home/chandranshu/zephyrproject/zephyr/zephyr-feature-auth_lib/samples/authentication/bluetooth/central_auth/prj.conf:55: warning: attempt to assign the value 'y' to the undefined symbol MBEDTLS_CIPHER_CBC_ENABLED

error: Aborting due to Kconfig warnings

CMake Error at /home/chandranshu/zephyrproject/zephyr/cmake/kconfig.cmake:251 (message):
command failed with return code: 1
Call Stack (most recent call first):
/home/chandranshu/zephyrproject/zephyr/cmake/app/boilerplate.cmake:608 (include)
CMakeLists.txt:4 (include)

-- Configuring incomplete, errors occurred!

**Comment by deangereaux** [comment]
You should be pulling the Zephyr code from this repo, branch `feature/auth_lib`.   I haven't merged the latest ZAUTH code with the latest Zephyr code.

**Comment by Chandranshu9** [comment]
So, without merging it with latest Zephyr code, How can I make it run? 
I have pulled the code from repo, branch feature/auth_lib. Was it to be pulled inside my zephyrRTOS code or in a separate directory like I did?
SInce I have pulled it outside in a separate directory therefore I am getting this as output:

usage: west [-h] [-z ZEPHYR_BASE] [-v] [-V] <command> ...
west: error: argument <command>: invalid choice: 'build' (choose from 'init', 'update', 'list', 'manifest', 'diff', 'status', 'forall', 'help', 'config', 'topdir', 'selfupdate')

And pulling it inside the zephyr code gives the same error I posted above.

**Comment by deangereaux** [comment]
The repo here (https://github.com/GoldenBitsSoftware/zephyr) is a fork of the zephyr repo, you should use this code.  To pull this code you can use the west command:  `west init -m https://github.com/GoldenBitsSoftware/zephyr <local dir>`

Then go through the usual steps to build as described in the Zephyr getting started guide here: https://docs.zephyrproject.org/latest/getting_started/index.html

I would suggest trying building the sample Blinky app first.

**Comment by Chandranshu9** [comment]
It worked, But the command you gave above is pulling the zephyr OS code and it doesn't have the authentication part in it, Is it the right path?
Should I try to clone the repo (https://github.com/GoldenBitsSoftware/zephyr) instead?

**Comment by deangereaux** [comment]
Assuming west cloned the repo to your <local di>r, then the ZAUTH code should be under lib/auth/*   If not, then check the branch, should be `feature/auth_lib`  if not then switch to that branch.

**Comment by Chandranshu9** [comment]
@deangereaux I tried to pull the code again since the auth part wasn't present in the above one, this is what I am getting now when executing **west init** in terminal
FATAL ERROR: already initialized in /home/chandranshu, aborting

How to resolve this.

**Comment by deangereaux** [comment]
I suggest reviewing the Getting Started guide here: https://docs.zephyrproject.org/latest/getting_started/index.html.  Ignore ZAUTH for now, just follow the Getting Started guide and try to build the Blinky example.   This will help you get familiar with the tools and the dev process.

**Comment by Chandranshu9** [comment]
Actually I did run the blinky example and the Bluetooth peripheral example earlier and it worked.

After I executed west init to pull the code, now whenever I try to execute west init again I am receiving this error message,

FATAL ERROR: already initialized in /home/chandranshu, aborting

I read somewhere it's related to ZEPHYR_BASE being set to different workspace.

**Comment by Chandranshu9** [comment]
hi @deangereaux , I reviewed the the starting guide and worked with zephyr code and did build most of the bluetooth programs as well, Now coming to ZAUTH, please can you tell me how to proceed, I would like to know whether I can clone the project in my directory rather than using west init as it caused me problems earlier.

Moreover should I first remove the zephyr code before cloning the ZAUTH code?

**Comment by Chandranshu9** [comment]
Hello @deangereaux, I pulled the recent ZAUTH code and tried out the bluetooth authentication code, Below are the errors I am getting:- $ bleauth/samples/authentication/bluetooth/peripheral_auth$ cmake -Bbuild_auth_ble_server -DBOARD=nrf52840_pca10056 -DCONF_FILE=dtls.prj.conf


Zephyr version: 2.1.0
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.5", minimum required is "3.4") 
-- git describe failed: fatal: not a git repository (or any of the parent directories): .git;
   BUILD_VERSION is left undefined
-- Selected BOARD nrf52840_pca10056
-- Found west: /home/chandranshu/.local/bin/west (found suitable version "0.8.0", minimum required is "0.6.0")
CMake Error at /home/chandranshu/bleauth/cmake/zephyr_module.cmake:45 (message):
  validation.invalid

   --- All found errors ---

  ["Key 'settings' was not defined.  Path: '/build'"]

  ERROR: Malformed "build" section in file:
  /home/chandranshu/bleauth/modules/hal/stm32/zephyr/module.yml

  <SchemaError: error code 2: Schema validation failed:

   - Key 'settings' was not defined. Path: '/build'.: Path: '/'>

Call Stack (most recent call first):
  /home/chandranshu/bleauth/cmake/app/boilerplate.cmake:458 (include)
  CMakeLists.txt:4 (include)


-- Configuring incomplete, errors occurred!

**Comment by Chandranshu9** [comment]
> The repo here (https://github.com/GoldenBitsSoftware/zephyr) is a fork of the zephyr repo, you should use this code. To pull this code you can use the west command: `west init -m https://github.com/GoldenBitsSoftware/zephyr <local dir>`
> 
> Then go through the usual steps to build as described in the Zephyr getting started guide here: https://docs.zephyrproject.org/latest/getting_started/index.html
> 
> I would suggest trying building the sample Blinky app first.

Hi @deangereaux , I changed the revision by using west -mr to featue/auth_lib and was able to pull your ZAUTH code without any errors, Now while following the getting started guide, I did west update but while doing **west zephyr-export** , I am getting invalid argument specified error. 

Please help me resolve the error.

**Comment by deangereaux** [comment]
@Chandranshu9   Good to see you’re making progress.  I do not have any insight as to why the west zephyr-export command is failing, you’ll have to debug.   I’ve been focusing on getting and official PR for submission to the Zephyr community, as such my responses will be delayed.

**Comment by Chandranshu9** [comment]
Hi @deangereaux , I am trying to debug the issue, Until then, Can you send me the captured packets between the two BLE devices showing the DTLS handshake via Wireshark or any other tool, Also Can you please share the screenshot of percentage of memory used when building the code and flashing.

I want to compare the resource utilization when using DTLS for authentication and when just using normal Just works method of authentication.

**Comment by deangereaux** [comment]
@Chandranshu9    Here's memory of build with Bluetooth and DTLS.  This was built for a Nordic nrf52840 Dev Kit. I don't have access to a BLE packet capture.

Memory region         Used Size  Region Size  %age Used
           FLASH:      300020 B         1 MB     28.61%
            SRAM:      120596 B       256 KB     46.00%
        IDT_LIST:         152 B         2 KB      7.42%


Also, I've submitted a PR to the Zephyr group for ZAUTH:  https://github.com/zephyrproject-rtos/zephyr/pull/31136
A new branch named, feature/zuath_lib, contains the submitted code.

**Comment by Chandranshu9** [comment]
@deangereaux Congratulations for submitting your PR. 
Regarding packet capture, Can you somehow provide the proof that the two BLE devices are using DTLS for authentication, I mean there has to be some method to cross check if the certificate chain is validated, right?

**Comment by deangereaux** [comment]
Certs are verified as part of the DTLS handshake, you can look at the code in auth_dtls.c which uses Mbedtls to perform the handshake.

**Comment by Chandranshu9** [comment]
@deangereaux Actually, what I meant was that after the handshake has been initiated and a secret key has been shared between the two devices, How can we confirm that Actually the communication is encrypted using that particular secret key. Is there any output/message displayed on the terminal/console mentioning this.

In short I want to verify all the steps that is happening in the DTLS handshake. Have you tested it?

**Comment by deangereaux** [comment]
@Chandranshu9  ZAUTH just authenticates the device, it does not provide the ability to send further application messages over the link (Bluetooth or Serial).  For DTLS, after the handshake is complete, that's it, ZAUTH reports this as a status message back to the calling code.  Future versions of ZAUTH may include the ability to send application messages via DTLS over Bluetooth and Serial. 

Again all of the DTLS handshake, secret key, cipher exchange, is all handled by the Mbed stack.  The code in auth_dtls.c calls into Mbed directly to perform the DTLS handshake.

This has been tested,  look at the samples in `samples/authentication`

**Comment by Chandranshu9** [comment]
@deangereaux , Thanks for clarifying this.

Regarding this statement:- "For DTLS, after the handshake is complete, that's it, ZAUTH reports this as a status message back to the calling code", Can you provide me the screenshot of some kind of message that is displayed, through which we can verify that the device is now authenticated.

Moreover I couldn't find auth_dtls.c anywhere, Can you please specify the exact location of the same?

**Comment by deangereaux** [comment]
Code is here:  https://github.com/GoldenBitsSoftware/zephyr/tree/feature/zauth_lib/lib/auth
On the `feature/zauth_lib` branch.

An example of the authentication status callback can be found in this sample:  https://github.com/GoldenBitsSoftware/zephyr/tree/feature/zauth_lib/lib/auth/main.c

Search for `auth_lib_init()` in main(), you'll see the `auth_status` function being set as the callback.  The status is defined by `enum auth_status`

**Comment by Chandranshu9** [comment]
Hi @deangereaux , Sorry for the long delay, I just have one last request, After building the code and flashing it on the devices, Can you take the screenshot where **(enum auth_status)** actually displays authentication successful message?
I want this to make sure that the code is actually running fine for your two devices so that I can also plan to buy Nordic nrf52840 Dev Kit and then start using your ZAUTH library.

**Comment by deangereaux** [comment]
@Chandranshu9   I don't have any screen shots, but if you look at the `printk()` statements in the samples main.c you'll see the messages that will be printed when the samples run.  Same is true for the status messages, look for the callback where the status messages are printed out, again in main.c. Also, I added two new calls,  auth_lib_dtls_send() and auth_lib_dtls_recv(), to send/recv messages via DTLS after a successful handshake.

**Comment by Chandranshu9** [comment]
@deangereaux Yes, I can see that in the code but since I am not able to run your code, I am not able to verify it and even use it in my project.
If you can somehow resolve my errors then it would really help me. Below I am attaching the screenshot of the error I am facing.
![Screenshot from 2021-02-19 19-54-23](https://user-images.githubusercontent.com/75840487/108516624-77a3bd80-72ec-11eb-903f-aaaf7aff3175.png)

**Comment by deangereaux** [comment]
1) You need to build from the top zephyr directory. (/home/dean/zephyr-auth/zephyr in the screenshot)
2) You're missing the full path to the sample dir   `west build -d build_auth_central -b nrf52840dk_nrf52840 -- -DCONF_FILE=dtls.prj.conf  samples/authentication/bluetooth/central_auth`

Also you might want to delete the `build_auth_central` directory before re-running west.

Note:   `samples/authentication/bluetooth/central_auth`
![zauth_build](https://user-images.githubusercontent.com/21283818/108761557-da22d680-7503-11eb-8897-76cceb1438b0.png)

**Comment by Chandranshu9** [comment]
@deangereaux  Thanks for the screenshot.

Can you provide me the screenshot of the flash monitor part as well, where we can monitor what has happened after the flash is done?

**Comment by deangereaux** [comment]
The ZAUTH PR has been closed due to lack of interested in the Zephyr community.  Closing this issue.
